### ISSUE TITLE
Adding a custom metric

### ISSUE THREAD

**Issue by mareksubocz** [tlpss/keypoint-detection#35]
Hi, thank you for this great repository!

I wanted to ask how can I add a simple custom metric, in my case it would be keypoint accuracy. It's mentioned as easy to do, but I couldn't figure it out. Preparing a pytorch-lightning Metric class is clear, but how can it be connected to the wandb logging?

Thanks in advance :D

**Comment by tlpss** [comment]
Hi @mareksubocz

The steps for adding a custom metric are 
- creating a PL metric class
- instantiating the classes with the desired parameters in the init method of the detector
- updating the metric during each val/test step
- logging the metric result after each epoch (and resetting it if needed)

The first part, you already have, which is great :+1: 

For the remaining 3 steps, I will point to the code for the AP metric, which you can then copy/modify:

- [creating the metric objects]( https://github.com/tlpss/keypoint-detection/blob/580365e73c30883a8f719b731d6332261940df51/keypoint_detection/models/detector.py#L129)
- [updating the metric in each step](https://github.com/tlpss/keypoint-detection/blob/580365e73c30883a8f719b731d6332261940df51/keypoint_detection/models/detector.py#L331)
- [logging the metric result](https://github.com/tlpss/keypoint-detection/blob/580365e73c30883a8f719b731d6332261940df51/keypoint_detection/models/detector.py#L360C9-L360C30)

You will note that the metric is not calculated every epoch to save some CPU/GPU cycles during training. 

I hope this helps, let me know if you have further questions! And I admit it is a little bit more elaborate than it should be,  I could make this easier in the future by automating the last 3 steps, since they are rather similar for most metrics.

**Comment by mareksubocz** [comment]
It worked! thank you!
